# Generated by Django 3.0.6 on 2020-06-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_user_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='userid',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Useractivity',
        ),
    ]
