# Generated by Django 3.0.6 on 2020-06-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200620_2211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together={('starttime', 'endtime')},
        ),
    ]
