# Generated by Django 3.0.6 on 2020-06-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200620_2219'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together=set(),
        ),
    ]
